### ISSUE TITLE
New Feature: Configurable User-Agent

### ISSUE THREAD

**Issue by richrumble** [SwensenSoftware/im-only-resting#74]
A vendor we connect to requires *something* as a user-agent, can you add the ability to send a UA string in GET requests etc... My pcap's show no UA is set or sent by default and I have yet to find a way to define one. Awesome tool BTW!

**Comment by stephen-swensen** [comment]
Glad you're liking IOR!

User-Agent is just a header so you can send whatever you want (including spoofing browsers or whatnot) in the Headers section of the Request form, e.g. 

    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
